from __future__ import annotations

from pathlib import Path


def generate_pytest_case(root: Path, plan: dict[str, object]) -> Path:
    run_id = str(plan["run_id"])
    domain = str(plan["domain"])
    safe_run_id = run_id.replace("-", "_")
    output_path = root / "tests" / "generated" / f"test_{safe_run_id}_{domain}.py"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_render_case(plan, safe_run_id, domain), encoding="utf-8")
    return output_path


def _render_case(plan: dict[str, object], safe_run_id: str, domain: str) -> str:
    run_id = str(plan["run_id"])
    target_feature = str(plan["target_feature"])
    steps = [_step_title(step) for step in plan.get("steps", [])]
    step_comments = "\n".join(f"    # Step {index}: {step}" for index, step in enumerate(steps, start=1))
    if step_comments:
        step_comments += "\n"
    return f'''"""Generated by leaf-test-author.

This is a pytest draft. It must be reviewed, validated, and connected to
domain AW/fixture code before it can count as a real device pass. The real
OpenHarmony execution path is the generated Hypium case.
"""

RUN_ID = "{run_id}"
DOMAIN = "{domain}"
TARGET_FEATURE = "{target_feature}"


def test_{safe_run_id}_{domain}():
{step_comments}    assert RUN_ID == "{run_id}"
    assert DOMAIN == "{domain}"
    assert TARGET_FEATURE == "{target_feature}"
'''


def _step_title(step: object) -> str:
    if isinstance(step, dict):
        return str(step.get("title", ""))
    return str(step)
